
*** src/inventory.rs:20:9: replace Inventory::add -> Result<(), Box<dyn Error>> with Ok(())

*** mutation diff:
--- src/inventory.rs
+++ replace Inventory::add -> Result<(), Box<dyn Error>> with Ok(())
@@ -12,23 +12,17 @@
     pub books: Vec<Book>,
 }
 
 impl Inventory {
     pub fn new() -> Self {
         Inventory { books: Vec::new() }
     }
     pub fn add(&mut self, b: Book) -> Result<(), Box<dyn Error>> {
-        let max_capacity = 30;
-        if self.books.len() < max_capacity {
-            self.books.push(b);
-            Ok(())
-        } else {
-            Err("Cannot add any more books".into())
-        }
+        Ok(()) /* ~ changed by cargo-mutants ~ */
     }
 
     pub fn remove(&mut self, b: usize) {
         self.books.remove(b);
     }
 
     pub fn update(
         &mut self,


*** /home/tode/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo build --tests --manifest-path /tmp/cargo-mutants-book_store-MpZ23b.tmp/Cargo.toml
   Compiling book_store v1.0.0 (/tmp/cargo-mutants-book_store-MpZ23b.tmp)
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s

*** result: Success

*** /home/tode/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo test --manifest-path /tmp/cargo-mutants-book_store-MpZ23b.tmp/Cargo.toml
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests src/lib.rs (target/debug/deps/book_store-dcbdbf2fee7dd28a)

running 14 tests
test tests::tests::test_add_max_capacity ... FAILED
test tests::tests::test_invalid_json_file ... ok
test tests::tests::test_remove_book ... FAILED
test tests::tests::test_display_books ... ok
test tests::tests::test_get_index ... FAILED
test tests::tests::test_invalid_json_file_2 ... ok
test tests::tests::test_non_existing_book ... ok
test tests::tests::test_add_book ... FAILED
test tests::tests::test_sell_book ... FAILED
test tests::tests::test_sell_more_than_available ... FAILED
test tests::tests::test_sell_book_2 ... FAILED
test tests::tests::test_sell_more_than_available_2 ... FAILED
test tests::tests::test_update_book ... FAILED
test tests::tests::test_update_book_1 ... FAILED

failures:

---- tests::tests::test_add_max_capacity stdout ----
thread 'tests::tests::test_add_max_capacity' panicked at src/tests.rs:174:9:
assertion failed: inventory.add(new_book).is_err()
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::tests::test_remove_book stdout ----
thread 'tests::tests::test_remove_book' panicked at src/tests.rs:53:56:
called `Option::unwrap()` on a `None` value

---- tests::tests::test_get_index stdout ----
thread 'tests::tests::test_get_index' panicked at src/tests.rs:115:9:
assertion `left == right` failed
  left: None
 right: Some(0)

---- tests::tests::test_add_book stdout ----
thread 'tests::tests::test_add_book' panicked at src/tests.rs:46:63:
called `Option::unwrap()` on a `None` value

---- tests::tests::test_sell_book stdout ----
thread 'tests::tests::test_sell_book' panicked at src/tests.rs:90:56:
called `Option::unwrap()` on a `None` value

---- tests::tests::test_sell_more_than_available stdout ----
thread 'tests::tests::test_sell_more_than_available' panicked at src/tests.rs:121:56:
called `Option::unwrap()` on a `None` value

---- tests::tests::test_sell_book_2 stdout ----
thread 'tests::tests::test_sell_book_2' panicked at src/tests.rs:99:56:
called `Option::unwrap()` on a `None` value

---- tests::tests::test_sell_more_than_available_2 stdout ----
thread 'tests::tests::test_sell_more_than_available_2' panicked at src/tests.rs:131:56:
called `Option::unwrap()` on a `None` value

---- tests::tests::test_update_book stdout ----
thread 'tests::tests::test_update_book' panicked at src/tests.rs:61:56:
called `Option::unwrap()` on a `None` value

---- tests::tests::test_update_book_1 stdout ----
thread 'tests::tests::test_update_book_1' panicked at src/tests.rs:76:56:
called `Option::unwrap()` on a `None` value


failures:
    tests::tests::test_add_book
    tests::tests::test_add_max_capacity
    tests::tests::test_get_index
    tests::tests::test_remove_book
    tests::tests::test_sell_book
    tests::tests::test_sell_book_2
    tests::tests::test_sell_more_than_available
    tests::tests::test_sell_more_than_available_2
    tests::tests::test_update_book
    tests::tests::test_update_book_1

test result: FAILED. 4 passed; 10 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass `--lib`

*** result: Failure(101)
